import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { randomUUID } from 'crypto';
import { prisma } from '../lib/prisma';
import { config } from '../config/env';
export interface UserProfile { id: string; email: string; name: string; userRank: string; points: number; role: string; guildName: string | null; isGuest?: boolean; }
function rankFor(points: number): string { if (points >= 5000) return 'Legendary Pathfinder'; if (points >= 2500) return 'Master Explorer'; if (points >= 1000) return 'Temple City Historian'; return 'Bhubaneswar Explorer'; }
export class AuthService {
  private static toProfile(user: any, isGuest = false): UserProfile { return { id: user.id, email: user.email, name: user.name, userRank: rankFor(user.points), points: user.points, role: user.role, guildName: user.guild?.name || null, ...(isGuest ? { isGuest: true } : {}) }; }
  private static issueToken(profile: UserProfile): string { return jwt.sign({ email: profile.email, role: profile.role, isGuest: profile.isGuest || false }, config.jwtSecret, { subject: profile.id, expiresIn: config.jwtExpiresIn as jwt.SignOptions['expiresIn'] }); }
  private static result(profile: UserProfile) { return { token: this.issueToken(profile), user: profile }; }
  static async register(email: string, password: string, name: string, guildName?: string) { const normalizedEmail = email.trim().toLowerCase(); const cleanName = name.trim(); if (!/^[^\s]+@[^\s]+\.[^\s]+$/.test(normalizedEmail)) throw { status: 400, message: 'A valid email is required' }; if (password.length < 8 || password.length > 128) throw { status: 400, message: 'Password must be between 8 and 128 characters' }; if (cleanName.length < 2 || cleanName.length > 80) throw { status: 400, message: 'Name must be between 2 and 80 characters' }; const passwordHash = await bcrypt.hash(password, 12); try { const user = await prisma.$transaction(async (tx) => { let guildId: string | undefined; const cleanGuild = guildName?.trim(); if (cleanGuild) guildId = (await tx.guild.upsert({ where: { name: cleanGuild }, update: {}, create: { name: cleanGuild, region: 'Odisha' } })).id; return tx.user.create({ data: { email: normalizedEmail, passwordHash, name: cleanName, guildId }, include: { guild: true } }); }); return this.result(this.toProfile(user)); } catch (error: any) { if (error?.code === 'P2002') throw { status: 409, message: 'Email already registered' }; throw error; } }
  static async login(email: string, password: string) { const normalizedEmail = email.trim().toLowerCase(); const user = await prisma.user.findUnique({ where: { email: normalizedEmail }, include: { guild: true } }); if (!user || !(await bcrypt.compare(password, user.passwordHash))) throw { status: 401, message: 'Invalid email or password' }; return this.result(this.toProfile(user)); }
  static async createGuest() { const id = randomUUID(); const user = await prisma.user.create({ data: { id, email: 'guest-' + id + '@guest.monumentquest.app', passwordHash: await bcrypt.hash(randomUUID(), 10), name: 'Guest Explorer' }, include: { guild: true } }); return this.result(this.toProfile(user, true)); }
  static async getProfile(userId: string) { const user = await prisma.user.findUnique({ where: { id: userId }, include: { guild: true } }); if (!user) throw { status: 404, message: 'User not found' }; return this.toProfile(user, user.email.endsWith('@guest.monumentquest.app')); }
}